name: "Dockerfile build"
on: 
  push:
    branches:
    - main
#  pull_request:
#    branches:
#      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get current version
      id: tailscale_version
      run: |
        app_version=$(cat VERSION.txt)
        
        echo $app_version
        echo "app_version=$app_version" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set values for tagging Docker image
      id: tags_meta
      uses: docker/metadata-action@v5
      with:
        images: "markoftw/tailscale"
        tags: |
          type=raw,value=${{ steps.tailscale_version.outputs.app_version }}
          type=raw,value=latest

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./markoftw.Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ steps.tags_meta.outputs.tags }}
#        build-args:
#          VERSION_SHORT=${{ steps.tailscale_version.outputs.app_version }}
#          VERSION_LONG=${{ steps.tailscale_version.outputs.app_version }}
#          VERSION_GIT_HASH=${{ github.sha }}
