name: Merge upstream main branch
on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'Marko Smej'
          git config --global user.email 'markoftw@users.noreply.github.com'
          git pull --unshallow  
          git remote add upstream https://github.com/tailscale/tailscale.git
          git fetch upstream
          git checkout main
          git merge --no-edit upstream/main
          git push origin main
          git push origin main --tags
          git push origin --tags
